### ISSUE TITLE
Can't configure the mod even with Mod Menu

### ISSUE THREAD

**Issue by ppblitto** [Fuzss/easymagic-fabric#1]
Even with the Menu Mod and the necessary library mods installed, it's not possible to access the configuration in-game. Also, when I go to the configuration folder in the game directory, there is just this:

![image](https://user-images.githubusercontent.com/57157437/143147283-e81e835d-0d48-4e8f-a034-d82afc7723e5.png)

**Comment by SzczurekYT** [comment]
Also have this, for me enchantment re rolling is too powerful and I can't diasble it

**Comment by SzczurekYT** [comment]
I found it, this config is per world and you can find it in world directory/serverconfig or when your are in a world  open using command: /config showfile easymagic SERVER
But still global config would be nice.

**Comment by Fuzss** [comment]
The world specific config file is a Minecraft Forge thing. I'm using the Forge system on Fabric as it makes maintaining mods for both mod loaders a lot more manageable.
World specific configs have the huge advantage of being automatically synced to clients when playing on a server which is an important thing to avoid desync issues.

You can set a global default config though. Copy the config file from your world to `.minecraft/defaultconfigs`. It will be used for all newly created worlds.

Oh an the in-game configuration is still being tested.

**Comment by CapoFantasma97** [comment]
> The world specific config file is a Minecraft Forge thing. I'm using the Forge system on Fabric as it makes maintaining mods for both mod loaders a lot more manageable. World specific configs have the huge advantage of being automatically synced to clients when playing on a server which is an important thing to avoid desync issues.
> 
> You can set a global default config though. Copy the config file from your world to `.minecraft/defaultconfigs`. It will be used for all newly created worlds.
> 
> Oh an the in-game configuration is still being tested.

I can't see the option to make rerolls cost resources, as stated in the mod FAQ. Instead, rerolls can only be disabled.

**Comment by p3lim** [comment]
@CapoFantasma97 If you're playing in a single player world, the config file should be inside your world, e.g. `saves/<worldname>/serverconfig/easymagic-server.toml` or something along those lines.

**Comment by Fuzss** [comment]
In-game mod configuration will be included in [Forge Config API Port](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric) when [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/8874) is merged with Forge, so it can be ported to Fabric.
