### ISSUE TITLE
i cant configure a mod

### ISSUE THREAD

**Issue by FifT3** [Fuzss/easymagic-fabric#2]
so i was playing on 1.18 then i suddenly remembered i needed to configure something in the Easy Magic mod but the button wasnt there btw i was using ModMenu so i can configure

**Comment by 3e2j** [comment]
can confirm

**Comment by Fuzss** [comment]
In-game mod configuration will be included in [Forge Config API Port](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric) when [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/8874) is merged with Forge, so it can be ported to Fabric.
