### ISSUE TITLE
[Suggestion] cycles enchs

### ISSUE THREAD

**Issue by Polarite** [Fuzss/easymagic-fabric#4]
Instead closing menu, reopening again, there should be a button on menu that rerolls enchs, and a keybind to automate it, cycle trades mod does that and I believe its pretty neat :3

**Comment by Fuzss** [comment]
You can simply take the enchanting item out of its slot and put it back in to recycle enchants. No need for an extra button.

Maybe I'll add an in-game description in the future to make it more obvious that the feature works like this.

**Comment by Polarite** [comment]
thing is you need to move the cursor away from the square, and doing that 50 times to get the enchant kinda gets annoying, a cycling key would be amazing

**Comment by Fuzss** [comment]
If you’re really having such a hard time finding a specific enchantment I can only recommend this mod of mine: https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-fabric
